### ISSUE TITLE
When it says token do I put in MY discord token?[QUESTION] 

### ISSUE THREAD

**Issue by ethicalhackslol** [0xSerpent/Cobra#3]
**What is your question?**
What do you wanna know / what do you need support with?

**What is the question related to? Be clear**
What's it related to?

**Additional Content**
Add any additional shit you wanna say.

**Comment by 0x-Stealth** [comment]
As in, Your personal account token? Or your Discord Bot token.

You're supposed to put in a bot token, I'm pretty sure putting in a User token wouldn't work.
